import { Expense, User } from "@/types";

export const INITIAL_USER: User = {
  id: "user_orbit_01",
  name: "Aarav Sharma",
  email: "aarav.sharma@spendwise.orbit",
  phone: "+91 98765 43210",
  avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80",
  accountStatus: "Verified Prime",
  memberSince: "January 2024",
  monthlyBudget: 50000,
  currency: "INR",
};

// Seed realistic transactions centered around current month so the hero orbit shows ₹27,000 outflow!
export function getInitialExpenses(): Expense[] {
  const now = new Date();
  const year = now.getFullYear();
  const month = String(now.getMonth() + 1).padStart(2, "0");
  const prevMonthNum = now.getMonth() === 0 ? 12 : now.getMonth();
  const prevYear = now.getMonth() === 0 ? year - 1 : year;
  const prevMonth = String(prevMonthNum).padStart(2, "0");

  return [
    // --- THIS MONTH EXPENSES (Summing to ₹27,000 outflow) ---
    {
      id: "exp_01",
      userId: "user_orbit_01",
      amount: 3250,
      description: "Artisan Coffee & Bistro Dinner",
      category: "Food & Dining",
      date: `${year}-${month}-02`,
      paymentMethod: "UPI",
      notes: "Dinner with team at Blue Tokai",
      type: "expense",
      createdAt: new Date(`${year}-${month}-02T19:30:00Z`).toISOString(),
      updatedAt: new Date(`${year}-${month}-02T19:30:00Z`).toISOString(),
    },
    {
      id: "exp_02",
      userId: "user_orbit_01",
      amount: 4500,
      description: "Monthly Metro & Airport Express Pass",
      category: "Transport",
      date: `${year}-${month}-03`,
      paymentMethod: "Credit Card",
      notes: "Auto-recharged transit pass",
      type: "expense",
      createdAt: new Date(`${year}-${month}-03T08:15:00Z`).toISOString(),
      updatedAt: new Date(`${year}-${month}-03T08:15:00Z`).toISOString(),
    },
    {
      id: "exp_03",
      userId: "user_orbit_01",
      amount: 6800,
      description: "Minimalist Ergonomic Keyboard & Mouse",
      category: "Shopping",
      date: `${year}-${month}-05`,
      paymentMethod: "Credit Card",
      notes: "Mechanical wireless setup for home office",
      type: "expense",
      createdAt: new Date(`${year}-${month}-05T14:20:00Z`).toISOString(),
      updatedAt: new Date(`${year}-${month}-05T14:20:00Z`).toISOString(),
    },
    {
      id: "exp_04",
      userId: "user_orbit_01",
      amount: 5200,
      description: "High-speed Fiber & Cloud Electric Grid",
      category: "Bills & Utilities",
      date: `${year}-${month}-07`,
      paymentMethod: "Net Banking",
      notes: "Airtel Xstream 1Gbps + electricity bill",
      type: "expense",
      createdAt: new Date(`${year}-${month}-07T11:00:00Z`).toISOString(),
      updatedAt: new Date(`${year}-${month}-07T11:00:00Z`).toISOString(),
    },
    {
      id: "exp_05",
      userId: "user_orbit_01",
      amount: 2850,
      description: "IMAX Laser Cinema & Dolby Sound",
      category: "Entertainment",
      date: `${year}-${month}-09`,
      paymentMethod: "UPI",
      notes: "Weekend premiere passes with friends",
      type: "expense",
      createdAt: new Date(`${year}-${month}-09T20:45:00Z`).toISOString(),
      updatedAt: new Date(`${year}-${month}-09T20:45:00Z`).toISOString(),
    },
    {
      id: "exp_06",
      userId: "user_orbit_01",
      amount: 2400,
      description: "Holistic Health Gym & Protein Nutrition",
      category: "Health & Wellness",
      date: `${year}-${month}-11`,
      paymentMethod: "UPI",
      notes: "Bi-weekly fitness nutrition supplements",
      type: "expense",
      createdAt: new Date(`${year}-${month}-11T16:00:00Z`).toISOString(),
      updatedAt: new Date(`${year}-${month}-11T16:00:00Z`).toISOString(),
    },
    {
      id: "exp_07",
      userId: "user_orbit_01",
      amount: 2000,
      description: "Generative AI Systems Masterclass",
      category: "Education",
      date: `${year}-${month}-12`,
      paymentMethod: "Debit Card",
      notes: "Specialized Deep Learning certification",
      type: "expense",
      createdAt: new Date(`${year}-${month}-12T10:00:00Z`).toISOString(),
      updatedAt: new Date(`${year}-${month}-12T10:00:00Z`).toISOString(),
    },
    // Total of above 7 expenses: 3250 + 4500 + 6800 + 5200 + 2850 + 2400 + 2000 = 27,000 ! Exact ₹27,000!

    // --- THIS MONTH INCOME ---
    {
      id: "inc_01",
      userId: "user_orbit_01",
      amount: 95000,
      description: "Principal Tech Consultant Compensation",
      category: "Investment",
      date: `${year}-${month}-01`,
      paymentMethod: "Net Banking",
      notes: "Monthly tech consulting retainership",
      type: "income",
      createdAt: new Date(`${year}-${month}-01T09:00:00Z`).toISOString(),
      updatedAt: new Date(`${year}-${month}-01T09:00:00Z`).toISOString(),
    },
    {
      id: "inc_02",
      userId: "user_orbit_01",
      amount: 25000,
      description: "Freelance Architecture Advisory",
      category: "Other",
      date: `${year}-${month}-10`,
      paymentMethod: "UPI",
      notes: "System design sprint milestone",
      type: "income",
      createdAt: new Date(`${year}-${month}-10T15:30:00Z`).toISOString(),
      updatedAt: new Date(`${year}-${month}-10T15:30:00Z`).toISOString(),
    },

    // --- LAST MONTH DATA (For growth trends and historical charts) ---
    {
      id: "exp_prev_01",
      userId: "user_orbit_01",
      amount: 4100,
      description: "Gourmet Dining Experience",
      category: "Food & Dining",
      date: `${prevYear}-${prevMonth}-08`,
      paymentMethod: "Credit Card",
      notes: "Celebration dinner",
      type: "expense",
      createdAt: new Date(`${prevYear}-${prevMonth}-08T20:00:00Z`).toISOString(),
      updatedAt: new Date(`${prevYear}-${prevMonth}-08T20:00:00Z`).toISOString(),
    },
    {
      id: "exp_prev_02",
      userId: "user_orbit_01",
      amount: 7500,
      description: "Boutique Apparel & Audio Gear",
      category: "Shopping",
      date: `${prevYear}-${prevMonth}-15`,
      paymentMethod: "UPI",
      notes: "Noise cancelling headphones",
      type: "expense",
      createdAt: new Date(`${prevYear}-${prevMonth}-15T13:00:00Z`).toISOString(),
      updatedAt: new Date(`${prevYear}-${prevMonth}-15T13:00:00Z`).toISOString(),
    },
    {
      id: "exp_prev_03",
      userId: "user_orbit_01",
      amount: 5100,
      description: "City Power & Water Grid",
      category: "Bills & Utilities",
      date: `${prevYear}-${prevMonth}-18`,
      paymentMethod: "Net Banking",
      notes: "Utility settlement",
      type: "expense",
      createdAt: new Date(`${prevYear}-${prevMonth}-18T10:00:00Z`).toISOString(),
      updatedAt: new Date(`${prevYear}-${prevMonth}-18T10:00:00Z`).toISOString(),
    },
    {
      id: "exp_prev_04",
      userId: "user_orbit_01",
      amount: 4800,
      description: "Urban Ride Pooling & Fuel",
      category: "Transport",
      date: `${prevYear}-${prevMonth}-22`,
      paymentMethod: "UPI",
      notes: "Cab bookings across city",
      type: "expense",
      createdAt: new Date(`${prevYear}-${prevMonth}-22T17:00:00Z`).toISOString(),
      updatedAt: new Date(`${prevYear}-${prevMonth}-22T17:00:00Z`).toISOString(),
    },
    {
      id: "inc_prev_01",
      userId: "user_orbit_01",
      amount: 95000,
      description: "Principal Tech Consultant Compensation",
      category: "Investment",
      date: `${prevYear}-${prevMonth}-01`,
      paymentMethod: "Net Banking",
      notes: "Monthly compensation",
      type: "income",
      createdAt: new Date(`${prevYear}-${prevMonth}-01T09:00:00Z`).toISOString(),
      updatedAt: new Date(`${prevYear}-${prevMonth}-01T09:00:00Z`).toISOString(),
    },
  ];
}
